// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: boilerplate.proto

package protobuf_boilerplate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGuestRequestVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGuestRequestVM) Reset() {
	*x = CreateGuestRequestVM{}
	mi := &file_boilerplate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGuestRequestVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGuestRequestVM) ProtoMessage() {}

func (x *CreateGuestRequestVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGuestRequestVM.ProtoReflect.Descriptor instead.
func (*CreateGuestRequestVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{0}
}

func (x *CreateGuestRequestVM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGuestRequestVM) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeleteGuestByIDRequestVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGuestByIDRequestVM) Reset() {
	*x = DeleteGuestByIDRequestVM{}
	mi := &file_boilerplate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGuestByIDRequestVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGuestByIDRequestVM) ProtoMessage() {}

func (x *DeleteGuestByIDRequestVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGuestByIDRequestVM.ProtoReflect.Descriptor instead.
func (*DeleteGuestByIDRequestVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteGuestByIDRequestVM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type FindAllGuestRequestVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Sorts         string                 `protobuf:"bytes,2,opt,name=sorts,proto3" json:"sorts,omitempty"`
	Take          uint64                 `protobuf:"varint,3,opt,name=take,proto3" json:"take,omitempty"`
	Skip          uint64                 `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllGuestRequestVM) Reset() {
	*x = FindAllGuestRequestVM{}
	mi := &file_boilerplate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllGuestRequestVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllGuestRequestVM) ProtoMessage() {}

func (x *FindAllGuestRequestVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllGuestRequestVM.ProtoReflect.Descriptor instead.
func (*FindAllGuestRequestVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{2}
}

func (x *FindAllGuestRequestVM) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *FindAllGuestRequestVM) GetSorts() string {
	if x != nil {
		return x.Sorts
	}
	return ""
}

func (x *FindAllGuestRequestVM) GetTake() uint64 {
	if x != nil {
		return x.Take
	}
	return 0
}

func (x *FindAllGuestRequestVM) GetSkip() uint64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type FindAllGuestResponseVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*GuestResponseVM     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllGuestResponseVM) Reset() {
	*x = FindAllGuestResponseVM{}
	mi := &file_boilerplate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllGuestResponseVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllGuestResponseVM) ProtoMessage() {}

func (x *FindAllGuestResponseVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllGuestResponseVM.ProtoReflect.Descriptor instead.
func (*FindAllGuestResponseVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{3}
}

func (x *FindAllGuestResponseVM) GetList() []*GuestResponseVM {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FindAllGuestResponseVM) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FindGuestByIDRequestVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindGuestByIDRequestVM) Reset() {
	*x = FindGuestByIDRequestVM{}
	mi := &file_boilerplate_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindGuestByIDRequestVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindGuestByIDRequestVM) ProtoMessage() {}

func (x *FindGuestByIDRequestVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindGuestByIDRequestVM.ProtoReflect.Descriptor instead.
func (*FindGuestByIDRequestVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{4}
}

func (x *FindGuestByIDRequestVM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GuestResponseVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestResponseVM) Reset() {
	*x = GuestResponseVM{}
	mi := &file_boilerplate_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestResponseVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestResponseVM) ProtoMessage() {}

func (x *GuestResponseVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestResponseVM.ProtoReflect.Descriptor instead.
func (*GuestResponseVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{5}
}

func (x *GuestResponseVM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GuestResponseVM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuestResponseVM) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GuestResponseVM) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GuestResponseVM) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *GuestResponseVM) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *GuestResponseVM) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type UpdateGuestByIDRequestVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGuestByIDRequestVM) Reset() {
	*x = UpdateGuestByIDRequestVM{}
	mi := &file_boilerplate_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGuestByIDRequestVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGuestByIDRequestVM) ProtoMessage() {}

func (x *UpdateGuestByIDRequestVM) ProtoReflect() protoreflect.Message {
	mi := &file_boilerplate_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGuestByIDRequestVM.ProtoReflect.Descriptor instead.
func (*UpdateGuestByIDRequestVM) Descriptor() ([]byte, []int) {
	return file_boilerplate_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateGuestByIDRequestVM) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGuestByIDRequestVM) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGuestByIDRequestVM) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_boilerplate_proto protoreflect.FileDescriptor

const file_boilerplate_proto_rawDesc = "" +
	"\n" +
	"\x11boilerplate.proto\x12\x14protobuf_boilerplate\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x14CreateGuestRequestVM\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"*\n" +
	"\x18DeleteGuestByIDRequestVM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"o\n" +
	"\x15FindAllGuestRequestVM\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x14\n" +
	"\x05sorts\x18\x02 \x01(\tR\x05sorts\x12\x12\n" +
	"\x04take\x18\x03 \x01(\x04R\x04take\x12\x12\n" +
	"\x04skip\x18\x04 \x01(\x04R\x04skip\"i\n" +
	"\x16FindAllGuestResponseVM\x129\n" +
	"\x04list\x18\x01 \x03(\v2%.protobuf_boilerplate.GuestResponseVMR\x04list\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"(\n" +
	"\x16FindGuestByIDRequestVM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcb\x01\n" +
	"\x0fGuestResponseVM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x05 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\a \x01(\tR\tupdatedBy\"X\n" +
	"\x18UpdateGuestByIDRequestVM\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress2\x85\x04\n" +
	"\vBoilerplate\x12`\n" +
	"\vCreateGuest\x12*.protobuf_boilerplate.CreateGuestRequestVM\x1a%.protobuf_boilerplate.GuestResponseVM\x12Y\n" +
	"\x0fDeleteGuestByID\x12..protobuf_boilerplate.DeleteGuestByIDRequestVM\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\fFindAllGuest\x12+.protobuf_boilerplate.FindAllGuestRequestVM\x1a,.protobuf_boilerplate.FindAllGuestResponseVM\x12d\n" +
	"\rFindGuestByID\x12,.protobuf_boilerplate.FindGuestByIDRequestVM\x1a%.protobuf_boilerplate.GuestResponseVM\x12h\n" +
	"\x0fUpdateGuestByID\x12..protobuf_boilerplate.UpdateGuestByIDRequestVM\x1a%.protobuf_boilerplate.GuestResponseVMB\x1aZ\x18pkg/protobuf_boilerplateb\x06proto3"

var (
	file_boilerplate_proto_rawDescOnce sync.Once
	file_boilerplate_proto_rawDescData []byte
)

func file_boilerplate_proto_rawDescGZIP() []byte {
	file_boilerplate_proto_rawDescOnce.Do(func() {
		file_boilerplate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boilerplate_proto_rawDesc), len(file_boilerplate_proto_rawDesc)))
	})
	return file_boilerplate_proto_rawDescData
}

var file_boilerplate_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_boilerplate_proto_goTypes = []any{
	(*CreateGuestRequestVM)(nil),     // 0: protobuf_boilerplate.CreateGuestRequestVM
	(*DeleteGuestByIDRequestVM)(nil), // 1: protobuf_boilerplate.DeleteGuestByIDRequestVM
	(*FindAllGuestRequestVM)(nil),    // 2: protobuf_boilerplate.FindAllGuestRequestVM
	(*FindAllGuestResponseVM)(nil),   // 3: protobuf_boilerplate.FindAllGuestResponseVM
	(*FindGuestByIDRequestVM)(nil),   // 4: protobuf_boilerplate.FindGuestByIDRequestVM
	(*GuestResponseVM)(nil),          // 5: protobuf_boilerplate.GuestResponseVM
	(*UpdateGuestByIDRequestVM)(nil), // 6: protobuf_boilerplate.UpdateGuestByIDRequestVM
	(*emptypb.Empty)(nil),            // 7: google.protobuf.Empty
}
var file_boilerplate_proto_depIdxs = []int32{
	5, // 0: protobuf_boilerplate.FindAllGuestResponseVM.list:type_name -> protobuf_boilerplate.GuestResponseVM
	0, // 1: protobuf_boilerplate.Boilerplate.CreateGuest:input_type -> protobuf_boilerplate.CreateGuestRequestVM
	1, // 2: protobuf_boilerplate.Boilerplate.DeleteGuestByID:input_type -> protobuf_boilerplate.DeleteGuestByIDRequestVM
	2, // 3: protobuf_boilerplate.Boilerplate.FindAllGuest:input_type -> protobuf_boilerplate.FindAllGuestRequestVM
	4, // 4: protobuf_boilerplate.Boilerplate.FindGuestByID:input_type -> protobuf_boilerplate.FindGuestByIDRequestVM
	6, // 5: protobuf_boilerplate.Boilerplate.UpdateGuestByID:input_type -> protobuf_boilerplate.UpdateGuestByIDRequestVM
	5, // 6: protobuf_boilerplate.Boilerplate.CreateGuest:output_type -> protobuf_boilerplate.GuestResponseVM
	7, // 7: protobuf_boilerplate.Boilerplate.DeleteGuestByID:output_type -> google.protobuf.Empty
	3, // 8: protobuf_boilerplate.Boilerplate.FindAllGuest:output_type -> protobuf_boilerplate.FindAllGuestResponseVM
	5, // 9: protobuf_boilerplate.Boilerplate.FindGuestByID:output_type -> protobuf_boilerplate.GuestResponseVM
	5, // 10: protobuf_boilerplate.Boilerplate.UpdateGuestByID:output_type -> protobuf_boilerplate.GuestResponseVM
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_boilerplate_proto_init() }
func file_boilerplate_proto_init() {
	if File_boilerplate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boilerplate_proto_rawDesc), len(file_boilerplate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boilerplate_proto_goTypes,
		DependencyIndexes: file_boilerplate_proto_depIdxs,
		MessageInfos:      file_boilerplate_proto_msgTypes,
	}.Build()
	File_boilerplate_proto = out.File
	file_boilerplate_proto_goTypes = nil
	file_boilerplate_proto_depIdxs = nil
}
